version: '3.7'
services:
  postgres:
    restart: always
    image: postgres:10
    env_file:
      - .env.prod.db
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend-prod:
    container_name: backend-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    env_file:
      - .env.prod
    volumes:
      - .:/backend
    depends_on:
      - postgres
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
